[opener]
edit = [
  { run = '/Applications/Cursor.app/Contents/Resources/app/bin/cursor "$@"', desc = "Cursor", block = true },
]
markdown = [
  { run = 'open -a "Mackdown" "$@"', desc = "Mackdown (view)", orphan = true },
  { run = '/Applications/Cursor.app/Contents/Resources/app/bin/cursor "$@"', desc = "Cursor (edit)", block = true },
  { run = 'glow -p "$@"', desc = "Glow (terminal)", block = true },
]

[open]
prepend_rules = [
  { url = "*.md", use = "markdown" },
  { url = "*.mdx", use = "markdown" },
  { url = "*.markdown", use = "markdown" },
]

[plugin]
prepend_previewers = [
  { mime = "text/markdown", run = "glow" },
]
